spring.application.name=demoMVCSecurity


spring.datasource.url=jdbc:mysql://localhost:3306/employee_management
spring.datasource.username=root
spring.datasource.password=IJSE@1234


#use to dev testing
logging.level.org.springframework.jdbc.core=TRACE
